# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/STOOMBOOT_PROJECTS/Research/MAYAPYTHON/Materialsetuper/SassyMaterialsUI.ui'
#
# Created: Tue Aug 10 13:43:13 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(658, 650))
        MainWindow.setMaximumSize(QtCore.QSize(658, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 381, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.button_browse_metalness = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_metalness.setObjectName("button_browse_metalness")
        self.gridLayout.addWidget(self.button_browse_metalness, 2, 3, 1, 1)
        self.check_metalness = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_metalness.setChecked(True)
        self.check_metalness.setObjectName("check_metalness")
        self.gridLayout.addWidget(self.check_metalness, 2, 0, 1, 1)
        self.check_reflectivity = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_reflectivity.setChecked(False)
        self.check_reflectivity.setObjectName("check_reflectivity")
        self.gridLayout.addWidget(self.check_reflectivity, 3, 0, 1, 1)
        self.check_normal = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_normal.setChecked(True)
        self.check_normal.setObjectName("check_normal")
        self.gridLayout.addWidget(self.check_normal, 6, 0, 1, 1)
        self.button_browse_height = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_height.setObjectName("button_browse_height")
        self.gridLayout.addWidget(self.button_browse_height, 7, 3, 1, 1)
        self.button_browse_roughness = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_roughness.setObjectName("button_browse_roughness")
        self.gridLayout.addWidget(self.button_browse_roughness, 1, 3, 1, 1)
        self.line_diffuse = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_diffuse.setObjectName("line_diffuse")
        self.gridLayout.addWidget(self.line_diffuse, 0, 2, 1, 1)
        self.line_metalness = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_metalness.setObjectName("line_metalness")
        self.gridLayout.addWidget(self.line_metalness, 2, 2, 1, 1)
        self.button_browse_diffuse = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_diffuse.setObjectName("button_browse_diffuse")
        self.gridLayout.addWidget(self.button_browse_diffuse, 0, 3, 1, 1)
        self.check_opacity = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_opacity.setChecked(False)
        self.check_opacity.setObjectName("check_opacity")
        self.gridLayout.addWidget(self.check_opacity, 5, 0, 1, 1)
        self.check_roughness = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_roughness.setChecked(True)
        self.check_roughness.setObjectName("check_roughness")
        self.gridLayout.addWidget(self.check_roughness, 1, 0, 1, 1)
        self.line_roughness = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_roughness.setObjectName("line_roughness")
        self.gridLayout.addWidget(self.line_roughness, 1, 2, 1, 1)
        self.button_browse_normal = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_normal.setObjectName("button_browse_normal")
        self.gridLayout.addWidget(self.button_browse_normal, 6, 3, 1, 1)
        self.line_normal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_normal.setObjectName("line_normal")
        self.gridLayout.addWidget(self.line_normal, 6, 2, 1, 1)
        self.line_emissive = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_emissive.setObjectName("line_emissive")
        self.gridLayout.addWidget(self.line_emissive, 8, 2, 1, 1)
        self.line_reflectivity = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_reflectivity.setObjectName("line_reflectivity")
        self.gridLayout.addWidget(self.line_reflectivity, 3, 2, 1, 1)
        self.check_height = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_height.setChecked(True)
        self.check_height.setObjectName("check_height")
        self.gridLayout.addWidget(self.check_height, 7, 0, 1, 1)
        self.check_emissive = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_emissive.setChecked(False)
        self.check_emissive.setObjectName("check_emissive")
        self.gridLayout.addWidget(self.check_emissive, 8, 0, 1, 1)
        self.button_browse_opacity = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_opacity.setObjectName("button_browse_opacity")
        self.gridLayout.addWidget(self.button_browse_opacity, 5, 3, 1, 1)
        self.button_browse_reflectivity = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_reflectivity.setObjectName("button_browse_reflectivity")
        self.gridLayout.addWidget(self.button_browse_reflectivity, 3, 3, 1, 1)
        self.line_opacity = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_opacity.setObjectName("line_opacity")
        self.gridLayout.addWidget(self.line_opacity, 5, 2, 1, 1)
        self.check_diffuse = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_diffuse.setChecked(True)
        self.check_diffuse.setObjectName("check_diffuse")
        self.gridLayout.addWidget(self.check_diffuse, 0, 0, 1, 1)
        self.line_height = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_height.setObjectName("line_height")
        self.gridLayout.addWidget(self.line_height, 7, 2, 1, 1)
        self.button_browse_emissive = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_emissive.setObjectName("button_browse_emissive")
        self.gridLayout.addWidget(self.button_browse_emissive, 8, 3, 1, 1)
        self.line_refraction = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_refraction.setObjectName("line_refraction")
        self.gridLayout.addWidget(self.line_refraction, 4, 2, 1, 1)
        self.check_refraction = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_refraction.setChecked(False)
        self.check_refraction.setObjectName("check_refraction")
        self.gridLayout.addWidget(self.check_refraction, 4, 0, 1, 1)
        self.button_browse_refraction = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.button_browse_refraction.setObjectName("button_browse_refraction")
        self.gridLayout.addWidget(self.button_browse_refraction, 4, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(400, 10, 241, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.presetbox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.presetbox.setEditable(False)
        self.presetbox.setObjectName("presetbox")
        self.verticalLayout.addWidget(self.presetbox)
        self.button_readJSON = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_readJSON.setObjectName("button_readJSON")
        self.verticalLayout.addWidget(self.button_readJSON)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(400, 460, 241, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_materialname = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_materialname.setObjectName("line_materialname")
        self.verticalLayout_2.addWidget(self.line_materialname)
        self.button_creatematerial = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.button_creatematerial.setObjectName("button_creatematerial")
        self.verticalLayout_2.addWidget(self.button_creatematerial)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(400, 130, 241, 321))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.line_folder = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.line_folder.setObjectName("line_folder")
        self.verticalLayout_3.addWidget(self.line_folder)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.line_prefix = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.line_prefix.setText("")
        self.line_prefix.setObjectName("line_prefix")
        self.verticalLayout_3.addWidget(self.line_prefix)
        self.button_searchfolder = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_searchfolder.setObjectName("button_searchfolder")
        self.verticalLayout_3.addWidget(self.button_searchfolder)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(11, 30, 381, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.presetbox_prefix = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.presetbox_prefix.setEditable(False)
        self.presetbox_prefix.setObjectName("presetbox_prefix")
        self.horizontalLayout.addWidget(self.presetbox_prefix)
        self.button_resetnames = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_resetnames.setObjectName("button_resetnames")
        self.horizontalLayout.addWidget(self.button_resetnames)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 122, 31))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_5.setObjectName("label_5")
        self.check_UDIM = QtWidgets.QCheckBox(self.centralwidget)
        self.check_UDIM.setGeometry(QtCore.QRect(10, 550, 271, 21))
        self.check_UDIM.setObjectName("check_UDIM")
        self.check_invertopacity = QtWidgets.QCheckBox(self.centralwidget)
        self.check_invertopacity.setGeometry(QtCore.QRect(10, 580, 271, 21))
        self.check_invertopacity.setObjectName("check_invertopacity")
        self.button_about = QtWidgets.QToolButton(self.centralwidget)
        self.button_about.setGeometry(QtCore.QRect(340, 560, 51, 31))
        self.button_about.setObjectName("button_about")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Sassy Materials", None, -1))
        self.button_browse_metalness.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.check_metalness.setText(QtWidgets.QApplication.translate("MainWindow", "Metal", None, -1))
        self.check_reflectivity.setText(QtWidgets.QApplication.translate("MainWindow", "Reflectivity", None, -1))
        self.check_normal.setText(QtWidgets.QApplication.translate("MainWindow", "Normal", None, -1))
        self.button_browse_height.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.button_browse_roughness.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.line_diffuse.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Diffuse (color) map.", None, -1))
        self.line_diffuse.setText(QtWidgets.QApplication.translate("MainWindow", "Diffuse", None, -1))
        self.line_metalness.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Metalness map.", None, -1))
        self.line_metalness.setText(QtWidgets.QApplication.translate("MainWindow", "Metalness", None, -1))
        self.button_browse_diffuse.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.check_opacity.setText(QtWidgets.QApplication.translate("MainWindow", "Opacity", None, -1))
        self.check_roughness.setText(QtWidgets.QApplication.translate("MainWindow", "Rough", None, -1))
        self.line_roughness.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Roughness map.", None, -1))
        self.line_roughness.setText(QtWidgets.QApplication.translate("MainWindow", "Roughness", None, -1))
        self.button_browse_normal.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.line_normal.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Tangent Normal map.", None, -1))
        self.line_normal.setText(QtWidgets.QApplication.translate("MainWindow", "Normal", None, -1))
        self.line_emissive.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Emissive map.", None, -1))
        self.line_emissive.setText(QtWidgets.QApplication.translate("MainWindow", "Emission", None, -1))
        self.line_reflectivity.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Reflectivity/Specular map.", None, -1))
        self.line_reflectivity.setText(QtWidgets.QApplication.translate("MainWindow", "Reflectivity", None, -1))
        self.check_height.setText(QtWidgets.QApplication.translate("MainWindow", "Height", None, -1))
        self.check_emissive.setText(QtWidgets.QApplication.translate("MainWindow", "Emission", None, -1))
        self.button_browse_opacity.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.button_browse_reflectivity.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.line_opacity.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Opacity map.", None, -1))
        self.line_opacity.setText(QtWidgets.QApplication.translate("MainWindow", "Opacity", None, -1))
        self.check_diffuse.setText(QtWidgets.QApplication.translate("MainWindow", "Diffuse", None, -1))
        self.line_height.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Displacement/Height map.", None, -1))
        self.line_height.setText(QtWidgets.QApplication.translate("MainWindow", "Displacement", None, -1))
        self.button_browse_emissive.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.line_refraction.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Filename or autosearch keyword for Refraction map.", None, -1))
        self.line_refraction.setText(QtWidgets.QApplication.translate("MainWindow", "Refraction", None, -1))
        self.check_refraction.setText(QtWidgets.QApplication.translate("MainWindow", "Refraction", None, -1))
        self.button_browse_refraction.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Presets:", None, -1))
        self.presetbox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Material presets as defined in mat_setup.JSON", None, -1))
        self.button_readJSON.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Reread all JSON files and update the internal presets.", None, -1))
        self.button_readJSON.setText(QtWidgets.QApplication.translate("MainWindow", "Reread JSON", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Material Name:", None, -1))
        self.button_creatematerial.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Create material with checked maps.", None, -1))
        self.button_creatematerial.setText(QtWidgets.QApplication.translate("MainWindow", "Create Material!", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Root search folder", None, -1))
        self.line_folder.setToolTip(QtWidgets.QApplication.translate("MainWindow", "The Root search folder. If this is empty, all browse buttons will use the folder the project is located in.", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Browse root folder...", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Additional substring search:", None, -1))
        self.line_prefix.setToolTip(QtWidgets.QApplication.translate("MainWindow", "You can include something extra to search for in the texture files. This can be helpful if you have a folder with textures for more than one material in it.", None, -1))
        self.button_searchfolder.setText(QtWidgets.QApplication.translate("MainWindow", "Autosearch in folder..", None, -1))
        self.presetbox_prefix.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Naming convention presets as described in mat_prefix.JSON", None, -1))
        self.button_resetnames.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Reset all filename/search suffix boxes to conform to chosen preset", None, -1))
        self.button_resetnames.setText(QtWidgets.QApplication.translate("MainWindow", "Reset prefixes", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Texture names:", None, -1))
        self.check_UDIM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Enable Mari style UDIM properties for file nodes. Do not bother to put <udim> tags in the filenames, it\'ll take care of that too.", None, -1))
        self.check_UDIM.setText(QtWidgets.QApplication.translate("MainWindow", "Enable UDIM settings for textures?", None, -1))
        self.check_invertopacity.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Sometimes, you just get an inverted alpha/opacity/transparency map and that\'s ok. Shit happens, so just turn this on and we\'ll put a reverse in between.", None, -1))
        self.check_invertopacity.setText(QtWidgets.QApplication.translate("MainWindow", "Invert Opacity map?", None, -1))
        self.button_about.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Hey hey, everythings gonna be ok", None, -1))
        self.button_about.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

